---
# Copyright 2015, Jean-Philippe Evrard <jean-philippe@evrard.me>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Add the keepalived apt repository key
  apt_key:
    id: "{{ keepalived_repo_keyid }}"
    #url: "{{ keepalived_repo_keyurl }}"
    keyserver: "{{ keepalived_keyserver }}"
    state: present
  when: keepalived_use_latest_stable_ppa | bool
  tags:
    - keepalived-apt-keys

- name: Add the keepalived apt repository
  apt_repository:
    repo: "{{ keepalived_repo }}"
    update_cache: True
    state: present
  when: keepalived_use_latest_stable_ppa | bool
  register: add_apt_repository
  tags:
    - keepalived-repo

#TODO(evrardjp): Replace the next 2 tasks by a standard apt with cache
#when https://github.com/ansible/ansible-modules-core/pull/1517 is merged
#in 1.9.x or we move to 2.0 (if tested working)
- name: Check apt last update file
  stat:
    path: /var/cache/apt
  register: apt_cache_stat
  tags:
    - keepalived-apt-packages

- name: Update apt if needed
  apt:
    update_cache: yes
  when: >
    "ansible_date_time.epoch|float - apt_cache_stat.stat.mtime > {{cache_timeout}}" or
    add_apt_repository|changed
  tags:
    - keepalived-apt-packages

- name: Prevent keepalived from starting on install
  copy:
    dest: /etc/init/keepalived.override
    content: manual
  changed_when: False
  tags:
    - keepalived-config
    - keepalived-prevent-start

- name: install keepalived
  apt:
    pkg: keepalived
    state: "{{ keepalived_use_latest_stable | bool | ternary('latest','present') }}"
  tags:
    - keepalived-apt-packages